### ISSUE TITLE
Pretrained Model missing

### ISSUE THREAD

**Issue by XaiverYuan** [megvii-research/FSSD_OoD_Detection#9]
Hi I tried to click on the link in pretrained link in google cloud, but it returns 404 now
老哥，来个百度网盘也行

**Comment by andrehuang** [comment]
Hi! 

Sorry for the inconvenience, but this repository is no longer maintained. If you need pre-trained models, you can simply run the code in https://github.com/megvii-research/FSSD_OoD_Detection/tree/master/lib/training. The models can be trained on single GPU within hours. Our method is just post-processing trained models and can be applied to any pretrained models indeed.

**Comment by XaiverYuan** [comment]
ok, thank you
